[workspace]
authors = ["Stuart Berg <bergs@janelia.hhmi.org>"]
channels = ["flyem-forge", "conda-forge"]
name = "flyem-snapshot"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
bokeh = ">=3.9.1,<4"
confiddler = ">=0.1.5,<0.2"
holoviews = ">=1.23.1,<2"
hvplot = ">=0.12.2,<0.13"
jinja2 = ">=3.1.6,<4"
neuclease = ">=0.81.post0.dev106"
pyarrow = ">=24.0.0,<25"
requests = ">=2.34.2,<3"
ujson = ">=5.13.0,<6"
python-cityhash = ">=0.4.10,<0.5"
ngsidekick = ">=0.0.19,<0.1"