[project]
authors = ["Stuart Berg <bergs@janelia.hhmi.org>"]
channels = ["flyem-forge", "conda-forge"]
description = "Connectome reports, exports, and neuprint neo4j ETL"
name = "flyem-snapshot"
platforms = ["osx-64", "linux-64"]
# version = "0.1.10"

[tasks]

[environments]
update-service = ["update-service"]

[dependencies]
python = ">=3.12.8,<4"
bokeh = ">=3.6.2,<4"
confiddler = ">=0.1.5,<0.2"
holoviews = ">=1.20.0,<2"
hvplot = ">=0.11.1,<0.12"
jinja2 = ">=3.1.4,<4"
neuclease = ">=0.7.3.post0.dev11,<0.8"
pyarrow = ">=17.0.0,<18"
requests = ">=2.32.3,<3"
ujson = ">=5.10.0,<6"
python-cityhash = ">=0.4.7,<0.5"

[target.linux-64.dependencies]
apptainer = ">=1.3.2,<2"

[feature.update-service.dependencies]
neuprint-python = ">=0.5,<0.6"
