{% set data = load_setup_py_data() %}

package:
  name: flyem-snapshot

  version: {{ data['version'] }}

source:
  path: ..

build:
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  host:
    - python >=3.10
    - setuptools
    - versioneer
  run:
    - python >=3.10
    - bokeh
    - confiddler >=0.1.5
    - holoviews
    - hvplot
    - jinja2
    - neuclease >=0.7.3
    - neuprint-python >=0.5.1
    - pyarrow
    - requests
    - ujson
    - python-cityhash
    - google-api-python-client
    - google-cloud-sdk
    - google-cloud-storage

    # Required by bokeh for making PNGs
    - selenium
    - firefox
    - geckodriver

    # If I add apptainer as a linux-only dependency,
    # then I'll have to change this package not to be noarch anymore.
    # - apptainer  # [linux]


test:
  imports:
    - flyem_snapshot.outputs

about:
  home: https://github.com/janelia-flyem/flyem-snapshot
  summary: Generate connectome exports, neuprint databases and reports from flat files and DVID checkpoints.
  license: BSD-3-Clause
  license_file: LICENSE
