{% set data = load_setup_py_data() %}

package:
  name: flyem-snapshot

  version: {{ data['version'] }}

source:
  path: ..

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python >=3.10
    - setuptools
    - versioneer
  run:
    - python >=3.10
    - bokeh
    - confiddler >=0.1.5
    - holoviews
    - hvplot
    - jinja2
    - neuclease >=0.7.3
    - neuprint-python
    - pyarrow
    - requests
    - ujson
    - python-cityhash
    - apptainer  # [linux]

test:
  imports:
    - flyem_snapshot.outputs

about:
  home: https://github.com/janelia-flyem/flyem-snapshot
  summary: Generate connectome exports, neuprint databases and reports from flat files and DVID checkpoints.
  license: BSD-3-Clause
  license_file: LICENSE
